language: cpp

env:
  global:
    - APPID=pvr.hdhomerun

os: linux
dist: trusty
sudo: required
compiler:
  - gcc
  - clang

# Install dependencies
#
# Install any prerequisites or dependencies necessary to run our builds
#
before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth=1 https://github.com/xbmc/xbmc.git
  - cd xbmc/project/cmake/addons
  - mkdir -p build
  - cd build/
  - cmake ../bootstrap -DCMAKE_BUILD_TYPE=Debug
  - make -j3

# Actually build
#
script:
  - cd $TRAVIS_BUILD_DIR/
  - mkdir build
  - cd build
  - cmake -DADDONS_TO_BUILD=pvr.hdhomerun -DADDON_SRC_PREFIX=$TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../xbmc/addons $TRAVIS_BUILD_DIR/../xbmc/project/cmake/addons
  - make -j3;
